version: '4'

services:
    student-manage-website:
        platform: linux/amd64
        image: student-manage-website
        container_name: student-manage-website
        restart: always
        build:
            context: .
            dockerfile: Dockerfile

        ports:
            - 1311:1311
        networks:
            - student-manage-network

networks:
    student-manage-network:
        external: true
