export * from './classQueries'
export * from './courseQueries'
export * from './departmentQueries'
export * from './studentQueries'
export * from './subjectQueries'
export * from './syllabusQueries'
export * from './teacherQueries'
