export enum DATE_TIME_FORMAT {
    DATE_ONLY = 'DD/MM/YYYY',
    DATE_ONLY_REVERSE_HYPHEN = 'YYYY-MM-DD',
    DATE_TIME_WITH_TIMEZONE = 'YYYY-MM-DDTHH:mm:ss.SSSZ',
    FULL_DATE_TIME = 'DD/MM/YYYY HH:mm:ss',
    HOUR_AND_MINUTE = 'HH:mm',
    SHORT_DATE_TIME = 'HH:mm, DD/MM/YYYY',
    TIME_ONLY = 'HH:mm:ss.SSS',
}
