export enum QUERY_KEYS {
    CLASS = 'CLASS',
    CLASS_LIST = 'CLASS_LIST',
    CLASS_LIST_OPTIONS = 'CLASS_LIST_OPTIONS',
    COURSE = 'COURSE',
    COURSE_LIST = 'COURSE_LIST',
    COURSE_LIST_OPTION = 'COURSE_LIST_OPTION',
    DEPARTMENT = 'DEPARTMENT',
    DEPARTMENT_LIST = 'DEPARTMENT_LIST',
    STUDENT = 'STUDENT',
    STUDENT_LIST = 'STUDENT_LIST',
    SUBJECT = 'SUBJECT',
    SUBJECT_LIST = 'SUBJECT_LIST',
    SUBJECT_LIST_OPTIONS = 'SUBJECT_LIST_OPTIONS',
    SYLLABUS = 'SYLLABUS',
    SYLLABUS_LIST = 'SYLLABUS_LIST',
    SYLLABUS_LIST_OPTIONS = 'SYLLABUS_LIST_OPTIONS',
}

export const INITIAL_QUERY = {
    PAGE_SIZE: 10,
    PAGE_INDEX: 0,
    SEARCH_VALUE: '',
}
