export enum QUERY_KEYS {
    CLASS = 'CLASS',
    CLASS_LIST = 'CLASS_LIST',
    CLASS_LIST_OPTIONS = 'CLASS_LIST_OPTIONS',
    DEPARTMENT = 'DEPARTMENT',
    DEPARTMENT_LIST = 'DEPARTMENT_LIST',
    STUDENT = 'STUDENT',
    STUDENT_LIST = 'STUDENT_LIST',
}

export const INITIAL_QUERY = {
    PAGE_SIZE: 10,
}
